version: '3.8'
services:
  app:
    image: anatamann/remindme_bot:0.1.5
    container_name: remindme_bot_con
    environment:
      - TOKEN=${TOKEN}
    volumes:
      - remindme_bot_vol:/home/remindme_bot

volumes:
  remindme_bot_vol:
    external: true
